// DOM-emulation smoke checks, not a substitute for real-browser visual QA.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {parseHTML}=require('linkedom');
const {svgPathProperties}=require('svg-path-properties');
const {document,window}=parseHTML(fs.readFileSync('docs/index.html','utf8'));
window.Element.prototype.scrollTo=function(){};
const geometryCache=new Map();let geometryCalls=0;function pathGeometry(el){const d=el.getAttribute('d')||'M0 0';if(!geometryCache.has(d))geometryCache.set(d,new svgPathProperties(d));return geometryCache.get(d);}
window.Element.prototype.getTotalLength=function(){geometryCalls++;return pathGeometry(this).getTotalLength();};
window.Element.prototype.getPointAtLength=function(n){geometryCalls++;return pathGeometry(this).getPointAtLength(n);};
const registered={};document.modelContext={registerTool:t=>registered[t.name]=t};
const ctx=vm.createContext({document,window,console,Math,AbortController,requestAnimationFrame:()=>{},setTimeout:()=>0,clearTimeout:()=>{},URL,Blob});
for(const name of ['control-core','fiber-model','field-model','optics','model-ui','experiments','app','webmcp'])vm.runInContext(fs.readFileSync('docs/'+name+'.js','utf8'),ctx,{filename:name+'.js'});
const run=s=>vm.runInContext(s,ctx),query=s=>document.querySelector(s);
const savePlot=(id,name)=>{fs.mkdirSync('.sites-runtime/qa',{recursive:true});const copy=query(id).cloneNode(true);for(const el of [...copy.querySelectorAll('path,polyline,circle,rect')].reverse()){const ref=el.nextSibling;while(el.firstChild)el.parentNode.insertBefore(el.firstChild,ref);}let svg=copy.outerHTML.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" ').replace('><','><style>text{font-family:Microsoft YaHei,sans-serif}</style><rect width="100%" height="100%" fill="#13292f"/><');fs.writeFileSync('.sites-runtime/qa/'+name+'.svg',svg);};
assert.equal(document.querySelectorAll('#component-list button').length,9);
assert.equal(Object.keys(registered).length,4);
for(const id of run('components.map(c=>c.id)')){run(`selectComponent('${id}')`);assert(query('#view-title').textContent&&!query('#view-title').textContent.includes('特写'));for(const el of document.querySelectorAll('#module-parameters .control-block')){const p=run('parameterSpecs').find(p=>p.id===el.querySelector('input').id);assert.equal(!el.hidden,p.modules.includes(id),'module controls '+id);}}
run("setView('overview')");for(const coil of document.querySelectorAll('.fiber-coil'))assert(query('#pulse-track').getAttribute('d').includes(coil.getAttribute('d')));
assert.deepEqual(Array.from(run("parameterSpecs.filter(p=>['pre1','pre2','pre3'].some(id=>p.modules.includes(id))).map(p=>p.id)")),['pre1Length','pre2Length','pre3Length','ld1','ld2','ld3']);assert.equal(run("parameterSpecs.find(p=>p.id==='stretch').max"),1000);assert.equal(run('state.stretch'),1000);assert.equal(run('state.ld2'),1);assert.equal(run('state.ld3'),1);
assert(!query('#optical-diagram').textContent.includes('PM980'));assert(!query('#optical-diagram').textContent.includes('二级预放'));assert(query('.overview-aom'));assert(query('.overview-compressor'));assert(query('.output-temporal-pulse'));assert(query('.free-space-beam'));assert(!document.querySelector('[data-component="endcap"]'));
for(const n of [1,2,4,37,100]){registered.configure_cpa_simulation.execute({pickEvery:n});run("selectComponent('aom');optical.progress=0;drawTravellingPulse()");assert.equal(query('#aom-train').querySelectorAll('path').length,n);assert.equal(query('.input-reference-pulses').querySelectorAll('path').length,n);run('optical.progress=.5;drawTravellingPulse()');assert.equal(query('#aom-train').querySelectorAll('path').length,1);assert.equal(run('state.rate'),1000/n);}savePlot('#optical-diagram svg','aom100');
for(const id of ['seed','cfbg','pre1','pre2','pre3','coupler']){run(`selectComponent('${id}')`);assert(!query('#module-experiment').hidden);for(const chart of ['temporal','spectral']){const q='#'+chart+'-field svg';assert(query(q).getAttribute('aria-label').includes('左轴'));assert(query(q).querySelector('.field-intensity'));assert(query(q).querySelector('.coherent-phase'));if(chart==='spectral')assert(query(q).textContent.includes('绝对波长'));savePlot(q,id+'-'+chart);}if(id==='cfbg'){const before=query('#temporal-field').innerHTML;registered.configure_cpa_simulation.execute({stretch:200});assert.notEqual(query('#temporal-field').innerHTML,before);}}

run("selectComponent('coupler')");assert(!query('#pump').closest('.control-block').hidden);assert(!run('parameterSpecs.some(p=>p.id==="coupling")'));assert(query('#fiber-readout').textContent.includes('固定 0.8 m'));
run("selectComponent('poweraom')");registered.configure_cpa_simulation.execute({pickEvery:4,stretch:1000,pump:70,ld2:1,ld3:1,target:8});const nominalTargetMax=run('targetPowerLimit()');assert.equal(Number(query('#target').max),nominalTargetMax);assert.equal(run('state.target'),8);registered.configure_cpa_simulation.execute({pump:0});const offTargetMax=run('targetPowerLimit()');assert(offTargetMax<nominalTargetMax);assert.equal(run('state.target'),offTargetMax);registered.configure_cpa_simulation.execute({pump:70,target:8});assert.equal(Number(query('#target').max),run('targetPowerLimit()'));assert.equal(registered.read_cpa_simulation.execute().pid.targetMax,run('targetPowerLimit()'));run("restartPID();for(let i=0;i<2000;i++)advancePowerLoop(.01);updateValues()");assert(query('#pid-power-read').textContent==='8.00 W');assert(Math.abs(run('values().power')-6)<.005);assert(Math.abs(run('values().pd4Power')-8)<.005);savePlot('#pid-main-chart','pid-plot');savePlot('#aom-response-chart','aom-response');assert.equal(Number(query('#aom-working-point').dataset.voltage),run('state.aomV'));assert.equal(Number(query('#aom-working-point').dataset.efficiency),run('aomEfficiency(state.aomV)'));assert(query('#aom-response-chart').parentNode.nextElementSibling.contains(query('#pid-main-chart')));assert(query('#gradient-controls').hidden);assert(!query('#power-loop-controls').hidden);assert(!query('#optical-diagram').textContent.includes('光栅 G1'));
run("selectComponent('compressor')");assert(query('#power-loop-controls').hidden);assert(query('#optical-diagram').textContent.includes('光栅 G1'));assert(!query('#optical-diagram').textContent.includes('PID'));
registered.configure_cpa_simulation.execute({pickEvery:4,stretch:150,motorPosition:16});const reachableTarget=run('Math.ceil((compressionBounds().min+5)/10)*10');registered.configure_cpa_simulation.execute({targetTau:reachableTarget,learningRate:2,motorStep:1,tolerance:1});const fieldBefore=query('#temporal-field')?.innerHTML;registered.run_cpa_experiment.execute({action:'gradient_start'});run('for(let i=0;i<500;i++)advanceGradient(.16);updateValues()');assert(run("gdStatus.startsWith('已收敛')"));assert(Math.abs(run('values().tau')-reachableTarget)<2);assert.equal(query('#module-experiment').dataset.compressorPosition,run('state.motorPosition.toFixed(8)'));assert.notEqual(query('#temporal-field').innerHTML,fieldBefore);assert(query('#gd-convergence').querySelectorAll('polyline').length===4);assert(query('#gd-landscape').textContent.includes('电机位置 x / mm'));assert(query('#optical-diagram').textContent.includes('PD5'));assert(query('#optical-diagram').textContent.includes('屋脊反射镜'));assert(query('#optical-diagram').textContent.includes(run('state.motorPosition.toFixed(3)')));savePlot('#gd-convergence','gd-convergence');savePlot('#gd-landscape','gd-landscape');savePlot('#temporal-field svg','compressed-temporal');savePlot('#spectral-field svg','compressed-spectral');
const segments=run('optical.segments');assert.equal(JSON.stringify(segments.filter(p=>p.comp).map(p=>[...p.comp])),JSON.stringify([[0,0],[0,.5],[.5,.5],[.5,1],[1,1]]));const widths=run('[0,.25,.5,.75,1].map(f=>stageShape("compressor",f).width)');assert(widths.every((w,i)=>i===0||w<widths[i-1]));assert.equal(document.querySelectorAll('.rainbow-ribbon').length,5);assert.equal(query('#roof-fold').getAttribute('points'),'935,415 935,585 990,530 990,360');

assert(run('state.optimizing'));const iteration=run('state.generation');run('for(let i=0;i<12;i++)advanceGradient(.16);updateValues()');assert.equal(run('state.generation'),iteration+12);assert(query('#gd-convergence').textContent.includes('等效脉宽'));assert(query('#temporal-field'));assert(query('#spectral-field'));
registered.configure_cpa_simulation.execute({targetTau:100});registered.run_cpa_experiment.execute({action:'gradient_start'});assert(!run('state.optimizing'));assert(run("gdStatus.includes('不可达')"));
assert.throws(()=>registered.configure_cpa_simulation.execute({kp:-1}));assert.throws(()=>registered.configure_cpa_simulation.execute({pickEvery:101}));assert.throws(()=>registered.configure_cpa_simulation.execute({pre1B:1}));assert.throws(()=>registered.configure_cpa_simulation.execute({manualVoltage:.4}));registered.configure_cpa_simulation.execute({powerLock:false,manualVoltage:.4});run('for(let i=0;i<1000;i++)advancePowerLoop(.01);updateValues()');assert(Math.abs(run('state.aomT')-run('aomEfficiency(.4)'))<1e-8);
run("selectComponent('aom')");query('#pickEvery-number').value='100';query('#pickEvery-number').dispatchEvent(new window.Event('change'));assert.equal(run('state.pickEvery'),100);
registered.configure_cpa_simulation.execute({pickEvery:4});run("selectComponent('compressor');applyExperimentPreset('stable');for(let i=0;i<500;i++)advanceGradient(.16);updateValues()");assert(run("gdStatus.startsWith('已收敛')"));
run("applyExperimentPreset('oscillate');for(let i=0;i<300;i++)advanceGradient(.16);updateValues()");assert(!run('state.optimizing')&&run("/搜索上限|边界限制/.test(gdStatus)"));savePlot('#gd-convergence','gd-unstable');
run("selectComponent('poweraom');applyExperimentPreset('oscillate');for(let i=0;i<3000;i++)advancePowerLoop(.01);updateValues()");assert(query('#pid-response-status').textContent.includes('明显振荡'));savePlot('#pid-main-chart','pid-unstable');
assert.throws(()=>registered.select_cpa_module.execute({module_id:'feedback'}));
for(let i=0;i<8;i++)run(`state.step=${i};renderLesson()`);
run('stop()');
run("setView('overview');refreshPulseMetrics()");
assert(query('#optical-diagram').textContent.includes('PM Yb 20/130'));
const overviewSegments=run('optical.segments');
for(let i=1;i<overviewSegments.length;i++){const a=overviewSegments[i-1].xy,b=overviewSegments[i].xy;assert(Math.hypot(a[a.length-2]-b[0],a[a.length-1]-b[1])<.05,'continuous track at segment '+i);}
const gains=run("['pre1','pre2','pre3','rod'].map(id=>{const s=optical.segments.find(p=>p.stage===id&&p.evolve);return [0,.25,.5,.75,1].map(t=>stageShape(s.stage,null,s.evolve,t).amp)})");for(const samples of gains)assert(samples.every((v,i)=>i===0||v>samples[i-1]),'gain grows inside medium');assert(gains.every((v,i)=>i===0||v.at(-1)>gains[i-1].at(-1)),'each amplifier output is stronger');
const stretching=run("optical.segments.filter(p=>p.stage==='cfbg'&&p.evolve).map(s=>[0,.25,.5,.75,1].map(t=>stageShape('cfbg',null,s.evolve,t).tauValue))");assert.equal(stretching.length,2);for(const samples of stretching)assert(samples.every((v,i)=>i===0||v>samples[i-1]));assert(Math.abs(stretching[0].at(-1)-stretching[1][0])<1e-6);
for(const vertical of [false,true])for(const direction of vertical?[1]:[-1,1]){const d=run(`circleRun(350,300,31,3,30,${vertical},${direction})`),g=new svgPathProperties(d),l=2*Math.PI*31;for(const t of [0,l,l+30,l*2+30,l*2+60]){const a=g.getPointAtLength(t+.05),b=g.getPointAtLength(t+.15);assert(vertical?b.y>a.y:(b.x-a.x)*direction>0,'coil tangent follows lead direction');}}
const callsBefore=geometryCalls,fieldCalls=run('fieldCache.key');run('const originalFieldPipeline=fieldPipeline;fieldPipeline=()=>{throw new Error("FFT pipeline requested inside frame")};');
const frameStart=performance.now();run('for(let i=0;i<600;i++){optical.progress=i/600;optical.clock+=1/60;drawTravellingPulse()}');const frameMs=(performance.now()-frameStart)/600;run('fieldPipeline=originalFieldPipeline');assert.equal(geometryCalls,callsBefore,'no geometry reads in animation frames');assert(frameMs<8,'CPU animation step budget');
const preserved=query('.overview-aom'),motor=query('#motor-assembly');run('state.motorPosition=15.2;refreshMotorGraphic()');assert.equal(query('.overview-aom'),preserved);assert.equal(query('#motor-assembly'),motor,'motor updates retain DOM');
console.log('Animation CPU mean '+frameMs.toFixed(3)+' ms/frame (DOM emulation; not browser FPS).');
assert.equal(run('state.optimizing'),false);assert.equal(run('values().power'),0);
console.log('PASS: initial page, 9 modules, contextual controls, circular paths, AOM N-to-1 animation, PID/GD UI and tools, target validation, all guide steps, reset.');
