const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({console,Math,Float64Array,Map});for(const f of ['control-core','fiber-model','field-model'])vm.runInContext(fs.readFileSync('docs/'+f+'.js','utf8'),ctx);const app=fs.readFileSync('docs/app.js','utf8');vm.runInContext(app.slice(0,app.indexOf('const components =')),ctx);const run=s=>vm.runInContext(s,ctx),near=(a,b,t)=>assert(Math.abs(a-b)<t,`${a} vs ${b}`);
assert.deepEqual(Array.from(run('Object.values(FIBERS).map(f=>f.maxPump)')),[1,9,27,300]);assert.deepEqual(Array.from(run("['pre1','pre2','pre3'].map(id=>FIBERS[id].defaultLength)")),[2,2,2]);near(run('fiberProperties("coupler").length'),.8,1e-12);
assert(run('fiberProperties("pre1").gamma>fiberProperties("pre2").gamma&&fiberProperties("pre2").gamma>fiberProperties("pre3").gamma&&fiberProperties("pre3").gamma>fiberProperties("coupler").gamma'));assert(run('Object.values(FIBERS).every(f=>f.beta2>0)'));
run('var pipeline=fieldPipeline()');near(run('fieldStats(pipeline.seed).tau'),300,1e-5);near(run('fieldStats(pipeline.cfbg).tau'),150000,.02);
let previous=.002;for(const id of ['pre1','pre2','pre3','coupler']){const record=run(`pipeline.${id}`),stats=run(`fieldStats(pipeline.${id})`);assert(Number.isFinite(stats.energy)&&Number.isFinite(stats.aseEnergy)&&stats.energy>previous);assert(record.amp.aseW>=0&&record.amp.absorbedPump>=0&&record.localB>=0);near(stats.energy,record.amp.signalOut/record.repHz*1e6,1e-6);assert(record.amp.signalOut+record.amp.aseW<=record.amp.signalIn+record.amp.pumpW+1e-6,'output does not exceed launched optical power');previous=stats.energy;}
const weak=run('solveAmplifier("pre2",2,2,.01,ASE_BINS.map(()=>0))'),strong=run('solveAmplifier("pre2",2,2,1,ASE_BINS.map(()=>0))');assert(weak.aseW>strong.aseW,'weaker signal leaves more inversion for ASE');assert(weak.inversion>strong.inversion);
const dark=run('solveAmplifier("pre2",0,2,.01,ASE_BINS.map(()=>0))');assert(dark.aseW<1e-6);assert(dark.signalOut<dark.signalIn,'unpumped Yb fiber reabsorbs signal');
assert(run('nonlinearIntegral(fiberProperties("pre2").gamma,4,1000,3)>nonlinearIntegral(fiberProperties("pre2").gamma,1,1000,3)'));assert(run('nonlinearIntegral(fiberProperties("pre2").gamma,2,2000,3)>nonlinearIntegral(fiberProperties("pre2").gamma,2,1000,3)'));
const one=run('(()=>{state.pre2Length=1;return fieldPipeline().pre2})()'),four=run('(()=>{state.pre2Length=4;return fieldPipeline().pre2})()');assert(four.gdd>one.gdd);assert.notEqual(four.localB,one.localB);assert(!run('isFieldParameter("pre2B")')&&!run('isFieldParameter("pre2Ase")')&&run('isFieldParameter("pre2Length")'));
run('state.pre2Length=2;var restored=fieldPipeline()');const stats=run('fieldStats(compressedField(16))');near(stats.energy,run('fieldStats(restored.coupler).energy'),.1);const bounds=run('compressionBounds()');assert(Number.isFinite(bounds.min)&&bounds.max>bounds.min&&bounds.best>=0&&bounds.best<=20);
for(const id of ['seed','cfbg','pre1','pre2','pre3','coupler']){const data=run(`fieldPlotData(fieldPipeline().${id})`);assert(data.spectral.every((p,i,a)=>Number.isFinite(p.intensity)&&Number.isFinite(p.phase)&&p.x>900&&(i===0||p.x>a[i-1].x)));assert(data.temporal.every(p=>Number.isFinite(p.intensity)&&Number.isFinite(p.phase)));}
const seedPeak=run('fieldPlotData(fieldPipeline().seed).spectral.reduce((a,b)=>a.intensity>b.intensity?a:b)');assert(Math.abs(seedPeak.x-1030)<.3);
run('state.seedTau=100;state.stretch=1000');run('var extreme=fieldPipeline().coupler');const plot=run('fieldPlotData(extreme)');assert(Number.isFinite(plot.stats.fwhm)&&plot.stats.energy>0);near(run('fieldStats(compressedField(20)).energy'),plot.stats.energy,.2);
run('state.ld1=0;state.ld2=0;state.ld3=0;state.pump=0');run('var unpumped=fieldPipeline().coupler');assert(run('fieldStats(unpumped).energy')>0);assert(run('fieldStats(unpumped).aseEnergy')<1e-3);
console.log('PASS: fixed fiber data, rate-equation gain/ASE, input saturation trend, pump and length response, derived GDD/B, 1 ns stretcher, Fourier fields and compressor.');
